---
name: CGI-Application-Plugin-ConfigAny
version: 0.01
author:
  - 'Bianka Martinovic <mab@cpan.org>'
abstract: Add Config::Any Support to CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::Any: 0.08
build_requires:
  Test::More: 0
provides:
  CGI::Application::Plugin::ConfigAny:
    file: lib/CGI/Application/Plugin/ConfigAny.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
